; ESPclock - ESP32 TM1652 display firmware
; This file is part of the ESPclock project fork by nltimv.
; Licensed under the GNU General Public License v3.0 (GPL-3.0)
; SPDX-License-Identifier: GPL-3.0-or-later

[env:esp32dev]
platform = espressif32
board = esp32dev
monitor_speed = 115200
framework = arduino
board_build.filesystem = littlefs
; To set a unique 4-character device ID (letters/digits), add a build flag, e.g.:
; build_flags = -D DEVICE_ID='"wY5h"'
lib_extra_dirs = ../../lib
lib_deps =
	bblanchon/ArduinoJson@^7.4.2
	maxint-solutions/TM16xx@^0.6.5
	mathieucarbou/AsyncTCP@^3.3.2
	mathieucarbou/ESPAsyncWebServer@^3.3.14
