#
# ESPclock - NGINX virtual host for the central device-finder web app
# This file is part of the ESPclock project fork by nltimv.
# Originally written by telepath9 (https://github.com/telepath9/ESPclock)
# Licensed under the GNU General Public License v3.0 (GPL-3.0)
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file has been modified by nltimv (https://github.com/nltimv).
#

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
